---
- name: Add Users
  hosts: all
  vars:
    ansible_python_interpreter: auto

  tasks:

  - name: Add users
    ansible.builtin.user:
      name: lp
      shell: /bin/bash
      create_home: yes
      state: present

  - name: Create directory .ssh
    ansible.builtin.file:
      path: /home/lp/.ssh
      state: directory
      owner: lp
      group: lp
      mode: '0700'

  - name: Add public key to authorized_keys
    ansible.builtin.copy:
      src: /home/leopoldo/.ssh/gcp_personal.pub
      dest: /home/lp/.ssh/authorized_keys
      owner: lp
      group: lp
      mode: '0600'

