- name: Install Tools
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.11

  tasks:
  - name: Install required packages Ubuntu/Debian
    ansible.builtin.apt:
      name:
        - git
        - net-tools
        - curl
        - wget
        - vim
      update_cache: yes
      state: present
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
